### ISSUE TITLE
Backup version is not upgraded when we generate a new recovery key

### ISSUE THREAD

**Issue by yostyle** [tchapgouv/tchap-android#1031]

**Comment by odelcroi** [comment]
Etude à mettre en P1

**Comment by yostyle** [comment]
Ceci n'est pas un bug. Sur Android quand on regénère le code de récupération les clés de cross signing et de secure backup (clé de chiffrement des rooms keys) sont conservées et chiffrées avec la nouvelle clé. Ceci permet de conserver la sauvegarde existante.

Sur le client web cette procédure est destructrice.
