### ISSUE TITLE
Invitations : forcer l'email en minuscules à l'envoi d'invitation

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-android#1034]
Lié à ce ticket : https://github.com/tchapgouv/tchap-support/issues/38

**Comment by yostyle** [comment]
il est préférable de réaliser cette modification sur le backend https://github.com/tchapgouv/tchap-support/issues/38#issuecomment-2079430695

**Comment by yostyle** [comment]
@NicolasBuquet c'est déjà en lowercase sur Android : https://github.com/tchapgouv/tchap-android/blob/main/vector/src/main/java/fr/gouv/tchap/core/dialogs/InviteByEmailDialog.kt#L44
