### ISSUE TITLE
Impossible de rejoindre un forum d'un autre homeserver depuis un lien généré sur mobile

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-android#1040]
L'activation de l'accès à un salon par lien depuis mobile (iOS ou Android) est moins complète que depuis web.

Exemple de lien d'activation créé depuis mobile :

    https://tchap.gouv.fr/#/room/#SalonFromTest1VUsOH5zJD8V:agent.dinum.tchap.gouv.fr

Exemple de lien d'activation créé depuis web :

    https://tchap.gouv.fr/#/room/!myhHblrznHhXmwYohG:agent.dinum.tchap.gouv.fr?via=agent.dinum.tchap.gouv.fr

Dans la création de lien sur mobile, il manque le paramètre via.

Ce paramètre est utile quand le lien est partagé à un utilisateur d'une instance qui n'est pas encore relié à l'instance hébergeant le salon. Ce lien sert à savoir sur quelle instance chercher le salon cible.

Ref : https://github.com/tchapgouv/tchap-ios/issues/875

**Comment by yostyle** [comment]
https://tchap.gouv.fr/#/room/#SalonFromTest1VUsOH5zJD8V:agent.dinum.tchap.gouv.fr : ce lien fait référence à un room alias

https://tchap.gouv.fr/#/room/!myhHblrznHhXmwYohG:agent.dinum.tchap.gouv.fr?via=agent.dinum.tchap.gouv.fr : ce lien fait référence à un roomId
