### ISSUE TITLE
Partage de géolocalisation : créer les pages FAQ

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-android#1044]
Le partage de géolocalisation (en temps réel ou non) va bientôt être déployé.

il faut créer une page de FAQ par plateforme pour expliquer aux utilisateurs : 
- où trouver la fonctionnalité
- comment paramétrer les autorisations pour autoriser la fonctionnalité

**Comment by yostyle** [comment]
https://aide.tchap.beta.gouv.fr/fr/article/comment-partager-sa-position-dans-tchap-1d9s61c/
