### ISSUE TITLE
Désactiver la fonctionalité des "Sondages"

### ISSUE THREAD

**Issue by yostyle** [tchapgouv/tchap-android#1066]
https://github.com/tchapgouv/tchap-product/issues/333

**Comment by yostyle** [comment]
La PR est prête. En attente du go du PO

**Comment by julie-ri** [comment]
@Delphgateau  je ne sais pas si tu es de mon avis mais pour moi on n'a pas statué sur le fait que cette feature est deceptive et qu'il faut supprimer  la fonctionnalité

**Comment by Delphgateau** [comment]
@julie-ri oui en effet, il me semble qu'on voulait avoir les stats du nombre de sondage créer depuis le lancement de la fonctionnalité. Nouveau ticket : https://github.com/tchapgouv/tchap-stats/issues/68

On pourrait aussi sonder les ambassadeurs pour leur demander leurs avis : "Lorsque vous souhaitez sonder les membres d'un salon, utilisez-vous plutôt la fonctionnalité "sondage" ou le vote par emojis ?"

**Comment by Delphgateau** [comment]
On fait quoi du coup ? Je lance un sondages utilisateurs ?

**Comment by Delphgateau** [comment]
Un sondage a été fait auprès des ambassadeurs, une partie l'utilise. Pour les utilisateurs, ils sont anonymes alors qu'ils ne le sont pas réellement : la commande /devtools, puis cocher Show hidden events in timeline permet de voir les votants.
On note un souhait (suggestions au support) pour certains de voir les votes, pour d'autres non.
En résumé, les sondages ne peuvent pas être anonymes et sont utilisés

Solution :

- ne pas les supprimer car la fonctionnalité est utilisée
- on pourra afficher par la suite le nom des votants https://github.com/tchapgouv/tchap-product/issues/135
- ne pas évoquer le fait qu'ils sont anonymes

On ferme ce ticket ou le débat n'est pas clos ?
