### ISSUE TITLE
[Rooms list] Last messages are stuck encrypted whereas the related keys have been received

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android#351]
bug to fix in Element: https://github.com/vector-im/element-android/issues/4867

**Comment by ClaireGizard** [comment]
Blocked by: https://github.com/vector-im/element-android/issues/4867

**Comment by giomfo** [comment]
need https://github.com/tchapgouv/tchap-android-v2/issues/403

**Comment by giomfo** [comment]
need Element v1.4.10
