### ISSUE TITLE
[Direct Message] Fix the first message sent twice

### ISSUE THREAD

**Issue by Florian14** [tchapgouv/tchap-android#364]
When creating a new direct message, the first message is sometimes (always?) sent twice with distinct event ids.

The plan is to verify first if the issue exists in Element-Android, then to fix it in the correct repository.

![image](https://user-images.githubusercontent.com/11990514/149516595-52fe65db-9509-41d9-a17d-daabc3b9069d.png)

**Comment by ClaireGizard** [comment]
I doesn't have the problem on Element Android v1.3.15.
