### ISSUE TITLE
[Room details] Wrong display on file infected

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android#398]
Wrong display on file infected. 
Device: Galaxy S8.
![file_infected](https://user-images.githubusercontent.com/15031750/151954533-7b40626d-3f00-4319-ba92-a20bba5d9e37.jpeg)

**Comment by giomfo** [comment]
Replace "Fichier Bloqué" with "Bloqué" or "Infecté"

**Comment by giomfo** [comment]
Test failed the description is cropped:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/8969772/162210148-d040d48b-62af-490a-bdb9-ef3aa81ff5f2.png">

it is displayed on only one line

**Comment by Claire1817** [comment]
I think is not related to this PR. 
Can you test on your device with a previous version please ? @giomfo

**Comment by giomfo** [comment]
we will use this issue to work on this new bug on infected attachment display

**Comment by giomfo** [comment]
test ok
