### ISSUE TITLE
Fix Github Action

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android#439]
- [x] Fix references to element-android in quality.yml
- [ ] Update sonarqube config in build.gradle: use a special config for Tchap -> may be commented?
- [ ] Add travis config pour Tchap
- [x] Update: PULL_REQUEST_TEMPLATE, reference to element-android (l17)

**Comment by giomfo** [comment]
TODO : We should plan a meeting with @jdauphant and @yostyle  in order to define the actual Actions we want for this repo
