### ISSUE TITLE
Set up the Secure Storage Support by forcing the recovery key

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android#458]
We want here to turn on the Secure storage without considering the cross signing feature by forcing the recovery key use
Tchap should not let the user defined its own secure phrase (phrase de securite)

**Comment by giomfo** [comment]
blocked by the current tests on cross-signing on Dev-infra

**Comment by giomfo** [comment]
We validated the cross-signing activation, we can work now on the secure storage set up

**Comment by odelcroi** [comment]
outdated issue
