### ISSUE TITLE
[Notification mode] Wrong mode is displayed when the mention only is selected on the web client

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android#464]
When the notification mode "mention only" is selected on the web client for an encrypted room, it must be displayed as disabled on mobile -> "none"

This is not the case currently, the selected mode on mobile is "All Messages", which is not correct
<img width="404" alt="image" src="https://user-images.githubusercontent.com/8969772/156222154-aa7c80e7-e12c-4110-8460-389d90340fbf.png">

**Comment by Claire1817** [comment]
PR: https://github.com/vector-im/element-android/pull/5547

**Comment by Claire1817** [comment]
would be fixed by https://github.com/tchapgouv/tchap-android-v2/issues/497 (rebase)

**Comment by giomfo** [comment]
test ok
