### ISSUE TITLE
Blank display name

### ISSUE THREAD

**Issue by Florian14** [tchapgouv/tchap-android#477]
After subscribing and connecting to Tchap, the display name of the user is blank (probably not computed yet). The problem is solved by joining a room or reopening the application.

We should first check if the problem exists in Element, then fix it in the right repository. 

<img width="437" alt="Capture d’écran 2022-03-08 à 14 00 21" src="https://user-images.githubusercontent.com/11990514/157439288-69969d2b-6c83-467c-af22-c4292d7f73d2.png">
<img width="437" alt="Capture d’écran 2022-03-08 à 14 00 13" src="https://user-images.githubusercontent.com/11990514/157439297-a6bdd4b4-c810-45f5-83ee-aa2a186cb359.png">

**Comment by Claire1817** [comment]
There is the same problem in Element.
![Screenshot_1646905930](https://user-images.githubusercontent.com/15031750/157636887-9958dadc-bc1a-4fcb-b3f7-3d7cd1a7f4e0.png)
![Screenshot_1646905941](https://user-images.githubusercontent.com/15031750/157636891-5f662618-24a6-4e01-af27-a0a781eb3a0a.png)

**Comment by Claire1817** [comment]
Issue on Element: https://github.com/vector-im/element-android/issues/5497

**Comment by giomfo** [comment]
would be fixed by the next rebase ( > v1.4.10 or v1.5.x)

**Comment by giomfo** [comment]
related to https://github.com/tchapgouv/tchap-android/issues/541
