### ISSUE TITLE
Read receipt in wrong order

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android#484]
### Steps to reproduce

The read receipt is in a wrong order. When some states events are hidden from the timeline, read receipts of the events are aggregated with the ones of the last message in the wrong order.
Web:
<img width="1008" alt="web" src="https://user-images.githubusercontent.com/15031750/157852968-7bba1576-5585-4690-9a2a-9a21332bc263.png">
Android:
<img width="438" alt="android" src="https://user-images.githubusercontent.com/15031750/157852997-697d8b51-e14c-4919-b33e-fb96de8d89bb.png">
<img width="438" alt="android2" src="https://user-images.githubusercontent.com/15031750/157853002-61fd83ca-1e55-4c0e-9efc-f62bf9b2d8ac.png">

### Outcome

We expect to have the read receipt in the good order.

### Will you send logs?

No

**Comment by Claire1817** [comment]
Issue in Element: https://github.com/vector-im/element-android/issues/5514

**Comment by Claire1817** [comment]
PR: https://github.com/vector-im/element-android/pull/5532

**Comment by giomfo** [comment]
would be fixed by https://github.com/tchapgouv/tchap-android-v2/issues/497 (rebase)
