### ISSUE TITLE
Les participants d'un salon ayant un compte inactif n'apparaissent plus en gris

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android#489]
Les participants d'un salon ayant un compte inactif n'apparaissent plus en gris. Impossible désormais pour un manager de relancer les agents de son équipe qui ont perdu leur compte.

Je ne peux pas faire mieux, car Tchap mobile interdit de prendre des captures d’écran…

![image](https://user-images.githubusercontent.com/1238254/158017349-08c838a6-2f4e-4877-bb4f-fe9be8e2fa08.png)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; SM-T725 Build/RP1A.200720.01; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "true"
default_app_language: "fr_FR"
device: "SM-T725"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30)"
server_version: "undefined"
theme: "light"
verbose_log: "OFF"

**Comment by jdauphant** [comment]
I have clean personnal data from the ticket : please don't do that

**Comment by giomfo** [comment]
I confirm this is a  regression
We would like to take time to think how restore this feature (expired account display) inside Element application itself

**Comment by jdauphant** [comment]
+1 need to be addressed in Element before being in Tchap
