### ISSUE TITLE
Enhance the DM header

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android#495]
We request here to split the contact display name on 2 lines in the DM header
- The actual name "Jean Dupond" as the main title
- the contact domain ("modernisation") as the subtitle

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1255251/158599926-081b78af-97b2-4b27-a25e-06b59675442f.png">

**Comment by giomfo** [comment]
@areox-net add this sub title will introduce a diff with Element-Android, because they recently remove the topic from the room title (see https://github.com/vector-im/element-android/issues/4642).
Our plan was to use this topic label to display the user domain...
Should we persist in this change now or discuss with Element team in order to add an optional subtitle in the model of the room header? cc @jdauphant

**Comment by areox-net** [comment]
I think it would be useful if Element made this subtitle space easily available as a customizable module. Hide it could also be an option. But looking at mainstream messaging app, it's easy to see how this space could be used in a lot of different ways.

**Comment by areox-net** [comment]
Indeed. Let's replace it with this
<img width="393" alt="Bubbles-01" src="https://user-images.githubusercontent.com/1255251/158599926-081b78af-97b2-4b27-a25e-06b59675442f.png">
