### ISSUE TITLE
If you reply to a redaction, the redacted text still appears

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android#496]
https://github.com/vector-im/element-android/issues/5546

**Comment by giomfo** [comment]
blocked see comments in element issue

**Comment by Claire1817** [comment]
Need: https://github.com/tchapgouv/tchap-android/issues/684

**Comment by giomfo** [comment]
@Claire1817 can you please update your comment, I think we will have to wait for another release
