### ISSUE TITLE
[Notifications] Play sound on each notification when the notification mode is "All messages"

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android#509]
#### What would you like to do?

Get all sound notifications of messages in a conversation

#### Why would you like to do it?

In the context of mountain rescue

#### How would you like to achieve it?

Activate an option

<img width="619" alt="image" src="https://user-images.githubusercontent.com/73166724/160139631-6e79edae-d2cc-4230-a923-892bc3f32131.png">

**Comment by giomfo** [comment]
related PR : https://github.com/vector-im/element-android/pull/5796

**Comment by Claire1817** [comment]
Wating for: https://github.com/tchapgouv/tchap-android/issues/596

**Comment by giomfo** [comment]
@Claire1817 can you please test in Tchap v2.3.2 and close this issue

**Comment by Claire1817** [comment]
Tests Ok :)
