### ISSUE TITLE
[MergedRoomCreationItem] DM: RoomDescriptionText use the roomName instead of memberName

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android#514]
https://github.com/vector-im/element-android/issues/5570

**Comment by Claire1817** [comment]
PR in element: https://github.com/vector-im/element-android/pull/5705

**Comment by Claire1817** [comment]
Will be integrate with the rebase against element 1.4.12.

**Comment by giomfo** [comment]
@Claire1817 can we close this issue? I think Tchap is not impacted anymore

**Comment by Claire1817** [comment]
Yes, i think too.
