### ISSUE TITLE
Hide sticker button

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android#520]
When I want to send a message
If I click on "+" and a sticker icon, I got the answer "Les intégrations sont désactivées".
We could hide this button "sticker" if it's anavailable.

**Comment by giomfo** [comment]
Effectively the attachments menu has been changed by Element so the sticker option appeared again

**Comment by giomfo** [comment]
Note : was done previously by https://github.com/tchapgouv/tchap-android-v2/issues/136

**Comment by jdauphant** [comment]
Can we have a feature flag in Element Android ? so we can hide with just a config ?

**Comment by giomfo** [comment]
test ok
