### ISSUE TITLE
Receipt of a notification that is not visible or does not exist 

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android#535]
### Steps to reproduce

User-Agent: "Tchap/2.0.3 (Linux; U; Android 6.0; F3311 Build/37.0.A.2.25; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200031] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "true"
default_app_language: "fr_FR"
device: "F3311"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "6.0 (API 23)"
server_version: "undefined"
theme: "system"
verbose_log: "OFF"

#### What did you expect?

Do not receive unnecessary notifications

#### What happened instead?

Ghost notifications

### Operating system version

Android 2.0.3

### Application version and app store

 olm version (3.2.7) 

### Will you send logs?

Yes

**Comment by jdauphant** [comment]
@Jonathan2051  "device_id" is private data, i have removed it and use the cleanup process to remove it from the ticket history

**Comment by Claire1817** [comment]
It's possible to have more details ?
Can we contact the user ?

**Comment by Jonathan2051** [comment]
The problem is still the same. The user still sees the notification icon above the application icon, but there is no notification when the application is opened. 

Link to the conversation (user's email address included) : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_f7cce939-adc6-4272-8e1f-a75a0e8cc068/

**Comment by appndigital** [comment]
Should be fixed by v2.4.4
