### ISSUE TITLE
Crash - Création de salon

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-android#580]
> L'arrêt de l'application se fait au moment de la création d'un groupe quand j'appuie sur la touche "enter" du clavier numérique du smartphone (Samsung) au lieu de scroler et d'appuyer sur la touche valider de l'application.

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; SM-A202F Build/RP1A.200720.01; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "SM-A202F"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) A202FXXU3CUJ2-REL"
server_version: "undefined"
theme: "light"

**Comment by Claire1817** [comment]
I didn't reproduce the bug. @JDixmier did you reproduce it ?

**Comment by JDixmier** [comment]
Yes I did.
When pushing "return" after typing the name of the room

**Comment by giomfo** [comment]
I don't reproduce in v2.4.1
