### ISSUE TITLE
Fail to validate cross-signing with Tchap Web v4

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android#614]
Approximate steps to reproduce : 
- Create a account and loging with https://app.preprod.tchap.incubateur.net/
- Login in Android last version
- Activate cross-signing on Android
- On https://app.preprod.tchap.incubateur.net/ click on "vérifier"
![image](https://user-images.githubusercontent.com/1238254/173930822-7ad78c5b-8feb-4493-8248-d4a8e81629df.png)
- Accept on android the verific-ation
- We got an error "Vous avez annulé la vérification dans votre autre appareil. Recommencer la vérification depuis la notification." 
![image](https://user-images.githubusercontent.com/1238254/173931052-10b58719-59ec-4918-baaf-9bbfb8c78abe.png)

It could be a bug on Tchap Web v4

**Comment by jdauphant** [comment]
I have also try to verify [/app.preprod.tchap.incubateur.net/](https://app.preprod.tchap.incubateur.net/) from the device Android before, It turn the red icon to a black icon : 
![image](https://user-images.githubusercontent.com/1238254/173931837-b6aa8b28-e9d7-481e-af8e-29f01368981d.png)

**Comment by jdauphant** [comment]
Also the android show "les clés privées ne sont pas connues" but the shield is green.
![image](https://user-images.githubusercontent.com/1238254/173932116-58de9d5c-e7ed-4836-8540-a00ccbb17649.png)

**Comment by giomfo** [comment]
> Also the android show "les clés privées ne sont pas connues" but the shield is green.

Did you enable the cross-signing on this session? or did you verify it with another session?

I'm afraid that the troubles you observed on preprod may be related to the fact that cross-signing support was not already enabled server side

**Comment by jdauphant** [comment]
I will redo the test after cross-signing activated server side
