### ISSUE TITLE
[Preprod] Analyse the consequences of the cross-signing enabling in Tchap-Android

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android#658]
We want here to test/observe the consequences in Tchap-web (by considering the current version deployed in Prod: v2.5.3)
We will consider the consequences in Tchap-iOS too, by considering mainly the new version v2.x.x (in beta test currently). 

~~Some tests should be planned by considering the current Prod version of Tchap-iOS [v1.2.3](https://github.com/tchapgouv/tchap-ios/releases/tag/tchap_v1.2.3). To be confirned~~

**Comment by giomfo** [comment]
- one more test on Tchap-web
- investigate the green shield on Tchap-ios
- test against Tchap-web v4 (demander une version en preprod)

**Comment by yostyle** [comment]
@Claire1817 added the test results in the notion document.
