### ISSUE TITLE
The shield don't appear when sync with QR Code with Tchap Web V4

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android#674]
# Step
- Connect new device on Tchap Web V4
- Click on verify on a connected Tchap Android
- Scan the Tchap Web v4 QR code with android 

No shield is showned on Android (but the Tchap Web v4 ask if a shield is showned)

![image](https://user-images.githubusercontent.com/1238254/178312253-f7a0aee1-034c-4251-89d3-5990d81cd507.png)

**Comment by Claire1817** [comment]
Problem comes from: https://github.com/tchapgouv/tchap-android/pull/296

**Comment by giomfo** [comment]
@Claire1817 don't you think we may show the shield again (I think we restore the shield in some other places, like sessions list, so it may be visible at the end of the verification)

**Comment by Claire1817** [comment]
This verification by QrCode is only available with the cross-signing. 
@jdauphant you had the possibility to do this verification because Tchap web v4 didn't disable the cross-signing.

@giomfo yes, i think it's a good idea to display all the shields with the cross-signing enabling.

**Comment by giomfo** [comment]
The plan is to restore the shield in 2 cases:
- during the QR code verification flow
- at the end of the verification
