### ISSUE TITLE
Réinitialisation de mdp - Bouton non cliquable

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-android#681]
Un utilisateur cherche à réinitialiser son mdp mais le bouton "Suivant" n'est pas cliquable (même en respectant les critères de mdp), donc il reste bloqué. 
App téléchargée il y a 2 jours donc à jour. 
Je n'ai pas reproduit le pb sur mon Samsung, même en essayant avec des mdp non conformes.

![c6de3a027f94fb95e100750b3dceed03ed19c53c-_1_](https://user-images.githubusercontent.com/45665538/179211647-50368c86-c50a-4d8a-baf1-0329b45c223b.jpg)

**Comment by Claire1817** [comment]
As tu des informations sur le modèle de son device ? la version de son OS ?

**Comment by yostyle** [comment]
Not reproduced
