### ISSUE TITLE
Notification icon is not in the good place

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android#694]
2 devices:
- Device A: Home on a Room part.
- Device B: Send a DM invitation to device A.
The device A receive the notification on the room part but the invitation is present on the dm part.

![Screenshot_1659606599](https://user-images.githubusercontent.com/15031750/182819444-f54df2bd-c2e8-4f7f-8974-035dfa62471e.png)
![Screenshot_1659606601](https://user-images.githubusercontent.com/15031750/182819467-f8ca4b0e-4b09-439b-9d30-9513e556238e.png)

_bug not reproduced if the device A is in the dm part when the invitation is sent_

**Comment by giomfo** [comment]
the layout will change soon
