### ISSUE TITLE
Forum creation: limited to my domain is not working

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android#695]
If we select the "limited to my domain", the forum is available in another server domain. 
Exemple: forum created on dinum account the forum is also available on social account.

**Comment by giomfo** [comment]
i'm wondering if this regression is not due to the fix of https://github.com/tchapgouv/tchap-android/issues/661

**Comment by Claire1817** [comment]
I didn't reproduce the bug. 
I check the code and it looks good.

**Comment by giomfo** [comment]
reproduced on Monday 8/8/2022 on Prod (I created "unfederated" a forum on agent.dinum, the tester account of social succeeded to join thie forum
