### ISSUE TITLE
Enable Danger

### ISSUE THREAD

**Issue by Florian14** [tchapgouv/tchap-android#714]
Element-Android v1.4.32 integrates [Danger](https://github.com/vector-im/element-android/blob/develop/docs/danger.md) in the CI build process.
Danger is a CI tool automating some common code reviews. It can check that a reviewer has been assigned to a PR, run the code quality checks (`Lint`, `ktlint`, `Detekt`…) and much more by adding [plugins](https://github.com/danger/awesome-danger#kotlin-danger-kotlin) to the process.
A bot will then post a comment in the PR in case of failure.

Since Tchap-Android has been rebased on that version, we have to configure Danger to restore some CI steps.
It requires the creation of a **new Github account** (eg. `TchapBot`) to check all the Tchap PRs, like Element [does](https://github.com/vector-im/element-android/blob/develop/docs/danger.md#danger-user).

It does not require adding the bot to the Tchap organization, just the creation of an access token scoped to `public_repo` as described in the Danger [guide](https://danger.systems/guides/getting_started.html).

**Comment by giomfo** [comment]
@jdauphant is that plan ok for you?

**Comment by jdauphant** [comment]
We can add Danger support, for access token, it should not be linked to individual account.

**Comment by jdauphant** [comment]
@pseudonyme21 is on working on similar things on thap-infra repository

**Comment by giomfo** [comment]
> We can add Danger support, for access token, it should not be linked to individual account.

If you use an individual account, it will appear on each comment, like "ElementBot" is the following screenshot: 
<img width="796" alt="image" src="https://user-images.githubusercontent.com/8969772/186639965-15d15f88-b6cb-4e6e-b04b-a9e7b447a96e.png">
I would advise to create a specific GH account

**Comment by giomfo** [comment]
@pseudonyme21 I let you check [our suggestion](https://github.com/tchapgouv/tchap-android/issues/714#issue-1350626293)

**Comment by jdauphant** [comment]
We prefere using Github Apps

**Comment by giomfo** [comment]
@jdauphant we agree with you according to https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps. But it seems not possible to use GH apps with Danger : https://github.com/danger/danger-js/issues/1199

How do you want to proceed ? which actions should we plan and who should work on them? 
- enable Danger by using GH Apps in order to check if there is issue or not
- ?
