### ISSUE TITLE
[2.4.2] Notifications problems appear to be back

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-android#736]
- All using 2.4.2
- All from Google Play Store
- On Android 8/10/11/12

People writing to the support for notification problems on Tchap Android : 

![Capture d’écran 2022-09-15 à 15 02 55](https://user-images.githubusercontent.com/45665538/190410659-b50ae71e-a0a4-44a2-a41a-add7f3b3ac70.png)

**Comment by Nivann** [comment]
Seems to be related to a network issue 

![image (1)](https://user-images.githubusercontent.com/99986548/191925349-0cfc67c4-e65c-4111-a5d9-7a8c87cef797.png)

**Comment by JDixmier** [comment]
Seems related :

> J'ai des soucis avec tchap. Les messages ne partent pas ou partent avec un délai très important (+ de 24h).
> Je ne reçois donc plus les notifications des salons malgré le test notification qui fonctionne. Il y a un test qui ne réussit pas et c'est celui du réseau. Que ce soit en wifi ou en 4G, le test push reste en jaune avec un point d'exclamation. J'ai déjà supprimé l'application, vidé le cache, les données etc... Rien n'y fait, les messages ne partent que quand ils veulent et non a l'instant T

**Comment by yostyle** [comment]
Related to https://github.com/vector-im/element-android/issues/6896
