### ISSUE TITLE
Update French translations in Tchap

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android#849]
Some strings are updating in Element. Following strings need to be updated in tchap only.

Quoi | Element | Tchap
-- | -- | --
Conversation many-to-many privé | Salon privé | Salon
Conversation many-to-many publique | Salon public | Forum
Clé de déchiffrement d’une session | Clés de déchiffrement | Clés Tchap
Backup de tous les messages chiffrés dans le cloud | Sauvegarde sécurisée | Sauvegarde automatique des messages
Email  | Email | Adresse mail  
Session | Session | Appareil
Accès annuaire des conv. many-to-many publiques | Parcourir les salons/Parcourir les salons publics | Rejoindre un forum

**Comment by yostyle** [comment]
_Clés de déchiffrement_ doesn't exist, we have _clés de chiffrement_ instead. Shoul we update the last one ?

**Comment by yostyle** [comment]
_email_ doesn't exist, we have _courriel_ instead. Should we update the last one ?
