### ISSUE TITLE
Vérifier que l'application demande REQUEST_IGNORE_BATTERY_OPTIMIZATIONS dans la version FDroid

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android#881]
Verifier que le manifest de Tchap FDroid inclut REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

**Comment by jdauphant** [comment]
> La permission de ne pas mettre l'application en veille n'est pas demandé par Tchap sur nos terminaux.
La gestion de cette permission ne relève pas d'ERCOM mais de son éditeur. La solution ERCOM Cryptosmart n’interagit pas avec l'économiseur de batterie Samsung/Android.
> Samsung Android 12

**Comment by yostyle** [comment]
![image](https://github.com/tchapgouv/tchap-android/assets/1191674/798c02a4-9976-4484-a182-954aa64d622b)
