### ISSUE TITLE
En tant que membre, je ne veux pas voir les changements d'avatar par défaut

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-android#904]
Same as https://github.com/tchapgouv/tchap-web-v4/issues/541 on web.

**Comment by yostyle** [comment]
La valeur est déjà a false par défaut 

https://github.com/tchapgouv/tchap-android/blob/ac2eb1e370f243eb80d6585fc0b0219966f92846/vector/src/main/res/xml/vector_settings_preferences.xml#L132

https://github.com/tchapgouv/tchap-android/blob/27934dcd4100ded87da05496fb49424dafacd25d/vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt#L478
