### ISSUE TITLE
La connexion biometrique se désactive fréquemment

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-android#921]
### Steps to reproduce

La connexion biometrique se désactive fréquemment

User-Agent: "Tchap/2.8.0 (samsung SM-S908B; Android 13; ; Flavour GooglePlay; MatrixAndroidSdk2 1.5.26)"
Version: "2.8.0 [402080002] (G-c2011a29-2023-04-07 16:00:36 +0200)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "true"
default_app_language: "fr_FR"
device: "SM-S908B"
locale: "fr_FR"
matrix_sdk_version: "1.5.26 (c2011a29)"
multi_window: "OFF"
olm_version: "3.2.12 - olm version (3.2.11) - 92769ce-2022-05-30 13:55:34 -0400"
os: "13 (API 33) S908BXXS4CWD3-REL"
server_version: "undefined"
theme: "system"

https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_b0e8cc20-0b8c-4880-829e-6fe883a29aab/

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by Delphgateau** [comment]
@odelcroi j'ai revu passer quelques tickets à ce sujet, celui là par ex :
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_34440d48-d8b6-4cf0-b428-ee6005d8b810/
