### ISSUE TITLE
[XSSS] Amélioration UX, wording et organisation des settings sécurité. 

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-android#926]
Suite à un travail d'analyse du parcours XSSS mono-device sur Android, voici une proposition de parcours amélioré et cohérente.
![XSSS-Monodevice-Android-Proposition](https://github.com/tchapgouv/tchap-android/assets/1255251/7db68dec-e114-4e10-9baf-685f4e968fbb)

Ici un résumé des modification à faire.

### 1. Changer l'ordre des sections des settings Sécurité.
- [x] Nouvel ordre:
1. Sauvegarde automatique des message
2. Appareils connectés
3. Signature croisée
4. Géstion des clés cryptographiques
5. Autres

### 2. Changer les noms des sections settings Sécurité.
- [x] Géstion des clés cryptographiques > **Clés Tchap**

### 3. Changer le formattage des titres:

- [x] Eliminer le text indent quand il s'agit pas d'un élément clicable
- [x] Augmenter la taille du titre des sections (17pt min)
- [x] Idéalement avoir une icone pour chaque ligne clicable.

### 4. Changer le wording de la section Sauvegarde automatique:
 
- [x] Texte explicatif à déplacer après le titre: Sauvegardez automatiquement vos messages et récupérez-les à tout moment à l’aide de votre Code de Récupération.

 Si activée: 
- [x] Bouton 1: picto actuel + "Générer un nouveau code"
- [x] Bouton 2: picto bouclier actuel (voir signature croisée) + "Gérér la sauvegarde"

Si pas activée:
- [x] Bouton 1:  Activer sur cet appareil

**Avant**
![image 10](https://github.com/tchapgouv/tchap-android/assets/1255251/9fa5ed2f-21dd-4411-8bfa-f7bfcd891082)

**Après**
![Android-Settings-Security](https://github.com/tchapgouv/tchap-android/assets/1255251/d1349060-e738-4ccc-9af7-9da907cab07d)

### 4. Changer le wording de la section Signature Croisée:
 Si activée: 
- [x] Bouton 1: picto actuel bouclier + "Signature croisée" "Activée sur cet appareil"

Si pas activée:
- [x] Bouton 1: picto actuel + "Activer sur cet appareil" 

### 5. Page génération code de Récupération
- [x] Titre: "Notez votre Code de Récupération"
- [x] Message "Notez ce code dans un endroit sûr.  Vous aurez à le copier / coller pour récupérer vos messages, donc évitez la capture d’écran.
Attention : c'est la seule fois que votre code est affiché !"
- [x] **Virer le bouton Continuer. L'appuis sur le bouton "Copier le Code" declanche directement la modale**
- [x] Titre de la modale: "Copier-le en lieu sûr" + texte de la modale "la" -> "le"
- [x] Message de la modale: 
"✓ Dans votre gestionnaire de mot de passe
✓ Sur une clé USB ou un disque de sauvegarde
✓ Sur votre ordinateur ou cloud"

**Après**
![Android-RecoveryCode](https://github.com/tchapgouv/tchap-android/assets/1255251/5ad14966-ffc8-4b8d-8297-7efe2fdddf62)

### 6. Page details Sauvegarde automatique...
- [x] Titre: Sauvegarde activée
- [x] Sous-titre: : cet appareil sauvegarde vos messages
- [x] Virer les autre details inutiles (Version, Algorithme)

**Après**
![Frame 2608905](https://github.com/tchapgouv/tchap-android/assets/1255251/3a17207d-6540-4b42-8b7e-a6e9c6644216)

### 7. Page récupération des message depuis device avec code
- [x] Titre: Récupération des messages
- [x] Bouton: Terminé > Terminer 

### 8. Modale suppresion de la sauvegarde
- [x] Message: "En supprimant la sauvegarde automatique, vous risquez de perdre vos messages."
- [x] Suite à la suppression revenir au settings Sécurité plutot que à la page de detail de la Sauvegarde

### 9. Toast de vérification appareil (suite à deconnexion)
- [x] Message: "Une fois votre appareil vérifié, vous pourrez récupérer vos messages."

**Après**
![Screenshot 2023-06-08 at 15 57 02](https://github.com/tchapgouv/tchap-android/assets/1255251/ab10fb07-48b8-4a63-8e72-97673fc86615)

### 10. Volet vérification appareil (suite à deconnexion)
- [x] Bouton: "Utilizer le Code de Récupération"

**Après**
![Frame 2608921](https://github.com/tchapgouv/tchap-android/assets/1255251/0ce6ad05-2ca3-4f9f-8c71-944e8631ab96)

### 11. Page insertion Code de Récuperation
- [x] Titre: "Récupération des messages"
- [x] Label input text: "Code de Récupération" (majuscules)
- [x] Message footer: "Vous avez perdu votre Code de Récupération ? Générez-en un nouveau."
- [x] Message si mauvais code: "Code erroné"

**Après**
![Frame 2608910](https://github.com/tchapgouv/tchap-android/assets/1255251/23d4ac16-fdbb-432b-9370-dd387df00904)

**Comment by areox-net** [comment]
@NicolasBuquet Voici les references des icones Material Design à utiliser:

- Appareils connectés: `hub`
- Exporter les clés: `upload`
- Importer les clés: `download`
- Proteger l’accès: `shield_lock`
- Clavier incognito: `keyboard`

Ca devrait ressembler à ça:
![Android-Settings-Security](https://github.com/tchapgouv/tchap-android/assets/1255251/2199e4d9-a3e6-4494-b845-3f0bbcbf8e16)

**Comment by NicolasBuquet** [comment]
Merci @areox-net

**Comment by NicolasBuquet** [comment]
@areox-net Tu avais cette option parce que le l'option avait déjà été activée sur ce compte.

Dans le code Android : 
```
        if (!vectorFeatures.tchapIsKeyBackupEnabled() || !info.isCrossSigningEnabled) {
            // Key backup is not supported or there is not cross signing, so we can remove the section
            secureBackupCategory.isVisible = false
```
si le `keyBackup` n'est pas activé sur le compte OU que le `cross-signing` n'est pas activé sur le compte, alors la section est masquée.

J'ai forcé l'affichage sur un nouveau compte qui n'avait pas ça, et ce n'était pas beau :
- dans un cas d'activation, ça tourne en boucle pour essayer d'activer le secure storage ("Activer sur cet appareil")
- dans l'autre cas ("Gérer la sauvegarde/Restaurer"), ça a mis le compte dans un état proche du coma.

**Comment by areox-net** [comment]
@NicolasBuquet D'accord, du coup notre analyse sur Android est un peu fausse.

**Comment by NicolasBuquet** [comment]
@areox-net En effet, j'ai du me mettre dans une configuration très particulière et peu commune.
J'ai refait des tests sur Android et web, et je n'arrive pas à reproduire ce cas.
On va donc partir du principe que pour 95% des utilisateurs, ces réglages sont disponibles.
