### ISSUE TITLE
L'activation du cross-signing sur Android ne l'active pas sur le client web

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-android#931]
En créant un nouveau compte Tchap sur Android, le cross-signing est automatiquement activé.

![image](https://github.com/tchapgouv/tchap-android/assets/18608158/73ce2d4f-ffe5-4e47-ac13-cb8660ba950a)
![image](https://github.com/tchapgouv/tchap-android/assets/18608158/bc13c1ce-a47c-4f30-901d-16de0aa765ed)

Les clés semblent être sur l'appareil Android mais pas sur le back-end ?

Mais ce cross-signing n'est pas marqué comme activé sur web sur le même compte.

![Screenshot 2023-06-20 at 11-50-32 Tchap](https://github.com/tchapgouv/tchap-android/assets/18608158/4ba62c2b-09cc-4e7d-a6c0-c2a0b5dfd414)
![Screenshot 2023-06-20 at 11-50-41 Tchap](https://github.com/tchapgouv/tchap-android/assets/18608158/36ebc2f5-0de1-45e7-a00d-56c39b0363b4)

Après vérification du client web contre le client Android, le cross-signing est marqué comme activé, mais les clés ne sont toujours pas stockées localement.

Après Activation sur le web de la signature croisée ("Activer sur l'appareil"), les clés semblent stockées dans le coffre.

![Screenshot 2023-06-20 at 12-13-00 Tchap](https://github.com/tchapgouv/tchap-android/assets/18608158/2ec7042a-bbe7-49df-af21-7758625898f5)

**Comment by yostyle** [comment]
@NicolasBuquet c'est une erreur d'affichage sur le client web.
