### ISSUE TITLE
Notifications non reçues

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-android#939]
Fréquemment, des utilisateurs se plaignent de ne pas recevoir les notifications sur Android.

Dans les paramètres avancés, une section "Cibles de notification" doit contenir ce que je pense être une série de tokens de push notifications (token utilisé pour identifier l'appareil cible d'une notification).

Il n'est pas normal qu'il puisse y en avoir plusieurs. Ces tokens peuvent être retirer par le bouton "Retirer".

S'il n'y a plus de token, un nouveau token sera généré au prochain lancement de l'application.

Il sera intéressant lors d'un prochain signalement support de demander à l'utilisateur de vider cette liste et de redémarrer l'application, puis de voir s'il reçoit à nouveau des notifications.

![image](https://github.com/tchapgouv/tchap-android/assets/18608158/72176877-c6cb-4673-8980-de314a612885)

UNe utilisatrice au support Crisp nous indique que la manipulation a résolu son problème : Une utilisatrice nous rapporte que cela a résolu son problème : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_94326ae7-bd89-46d5-9381-b329a78933be/

**Comment by jdauphant** [comment]
Est-ce que le fait que le serveur de push n'ai pas d'url public est un problème ?

**Comment by NicolasBuquet** [comment]
Non, un grand nombre d'utilisateurs reçoivent les notifications.
Et le mobile n'a jamais à joindre ce serveur. Le serveur dialogue avec les serveurs Push Notifications Servers de Apple et Google et ce sont eux qui poussent de l'info vers les mobiles.
Les mobiles n'ont jamais à pousser d'info vers notre serveur.

**Comment by jdauphant** [comment]
ok, sauf peut être pour le test de notification ?

**Comment by NicolasBuquet** [comment]
Oui, sauf pour le test de notification, qui du coup sur Tchap, est toujours en erreur. On va retirer ce test.

**Comment by NicolasBuquet** [comment]
Apparemment, cette piste de résolution semble sérieuse. Une utilisatrice nous rapporte que cela a résolu son problème : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_94326ae7-bd89-46d5-9381-b329a78933be/
Sûrement temporairement car plusieurs tokens vont être régénérés à un moment et le problème réapparaîtra.

**Comment by odelcroi** [comment]
> Apparemment, cette piste de résolution semble sérieuse. Une utilisatrice nous rapporte que cela a résolu son problème : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_94326ae7-bd89-46d5-9381-b329a78933be/ Sûrement temporairement car plusieurs tokens vont être régénérés à un moment et le problème réapparaîtra.

Est ce que ca vaudrait le coup de la documenter dans la FAQ ? https://aide.tchap.beta.gouv.fr/fr/article/je-ne-recois-pas-de-notifications-que-faire-android-cb53w7/ @NicolasBuquet
