### ISSUE TITLE
[XSSS] Amélioration UX, wording et organisation des settings sécurité (partie II, multidevice)

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-android#940]
Suite aux modification précedentes (#926) et à l'analyse du parcours XSSS multi-device sur Android et Web, voici des propositions d'amélioration

### 1. Section Sauvegarde automatique des messages
- [x] La section n'est pas affichée quand on crée son compte sur Android avant du web. Pourtant quand la Signature croisée est activée, cette section apparait d'un coup. 
@NicolasBuquet semble dire que la Signature croisée devrait etre activée automatiquement sur Android mais cela marche mal
- [x] Quand active, inverser l'ordre des boutons
- [x] Changer le bouton "Gérer la sauvegarde" > Récupérer mes messages
- [ ] BUG: Quand on active la fonction le bouton "Générer un nouveau code apparait" mais pas le deuxième bouton. L'autre bouton apparait si on sort et on rentre à nouveau dans les settings . Il faut forcer le rafraîchissement de la page

_Après_
![image](https://github.com/tchapgouv/tchap-android/assets/1255251/e9a1d050-d3f6-44dc-bd15-d2354f56ac24)

### 2. Détail Sauvegarde automatique des messages (appuis sur Gérer la sauvegarde)

- [x] Eliminer le bouton "Supprimer la sauvegarde"

_Avant_
![image](https://github.com/tchapgouv/tchap-android/assets/1255251/18a650f2-3840-406a-8dd0-8678ca4d8dd9)

_Après_
![image](https://github.com/tchapgouv/tchap-android/assets/1255251/c8d1876b-f354-4b32-930c-7ebae7c4db83)

### 3. Section Signature croisée
Cela est nécessaire si on arrive pas à activer la SC automatiquement
- [x] Quand désactivé ajouter une icon Android _cancel_ de la couleur #9B9B9B

_Après_
![image](https://github.com/tchapgouv/tchap-android/assets/1255251/2435f463-d2c9-4015-b603-4368731c964f)

### 4. Page détail Signature croisée
- [x] Eliminer la ligne rouge avec le detail. Le titre avec status suffit

_Avant_
![image](https://github.com/tchapgouv/tchap-android/assets/1255251/12d52a43-89ac-44a4-8de4-028811d285a5)

_Après_
![image](https://github.com/tchapgouv/tchap-android/assets/1255251/44fe9aaa-7c31-43ea-a18e-c83c7383e0ba)

**Comment by NicolasBuquet** [comment]
@areox-net Dans le point 4, la ligne rouge est en fait un bouton qui démarre une procédure de reset dela signature croisée (demande de mot de passe).

**Comment by areox-net** [comment]
@NicolasBuquet dans ce cas il faudrait changer le wording en "Réinitialiser".
On pourrait améliorer davantage ce bouton, mais je me dis que ce n'est pas un écran prioritaire et qu'il sera probablement améliorer sur Element X.
