### ISSUE TITLE
Test push indique "aucune connexion"

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-android#962]
Depuis quelques jours, des utilisateurs Android reçoive un message d'erreur lorsqu'ils tentent de "résoudre les problèmes de notification" : Quand ils cliquent sur "Tester le Push", le message d'erreur suivant s'affiche : "Aucun réseau, vérifier votre connexion internet", alors qu'ils sont connectés.
Exemple : 
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_9a62aa09-1d88-40d7-a02e-819bcae6bd7b/
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_8ce35998-6517-41e2-ae10-39facbb57912/
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_bb4a83a1-4fa1-435b-b588-5f96dbb993b4/

**Comment by NicolasBuquet** [comment]
Corrigé par cette PR https://github.com/tchapgouv/tchap-android/pull/951

A partir de la version 2.9.2

(les 3 tickets cités sont en 2.8.4).
