### ISSUE TITLE
Crash avec erreur "Max number of dynamic shortcuts exceeded"

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-android#964]
Ces crashs arrivent depuis quelques semaines.

Exemples : 
- https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_6061a845-105a-4cfa-9d21-7aa14de53696/
- https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_00c5f2cf-ee28-435c-9601-f4d18bb748b8/
- https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_f652aa1e-699a-450c-af88-e60959a96941/

**Comment by yostyle** [comment]
related to #469
